fix for binary operators not working for double quaternions (dquat) in some cases (" error C2440: 'return': cannot convert from 'donut::math::quat' to 'donut::math::quaternion<double>' "